version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WPP_INSTANCE_ID=${WPP_INSTANCE_ID}
      - WPP_INSTANCE_TOKEN=${WPP_INSTANCE_TOKEN}
      - WPP_CLIENT_TOKEN=${WPP_CLIENT_TOKEN}
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
    depends_on:
      - redis
    networks:
      - app-network